[tools]
7zip = "latest"
"aqua:ViRb3/wgcf" = "latest"
aws-cli = { version = "latest", symlink_bins = "true" }
bat = "latest"
btop = "latest"
bun = "latest"
cargo-binstall = "latest"
"cargo:tree-sitter-cli" = "latest"
delta = "latest"
fastfetch = "latest"
fd = "latest"
ffmpeg = "latest"
fzf = "latest"
gh = "latest"
"github:h4ckf0r0day/obscura" = { version = "latest", asset_pattern = "obscura-x86_64-linux-stealth.tar.gz" }
"github:iOfficeAI/OfficeCLI" = "latest"
"github:mikeleppane/envx" = "latest"
"github:rgwood/systemctl-tui" = "latest"
imagemagick = "latest"
jq = "latest"
lazydocker = "latest"
lazygit = "latest"
mpv = "latest"
neovim = "latest"
node = "26"
"npm:@agegr/pi-web" = "latest"
"npm:@earendil-works/pi-coding-agent" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:prettier" = "latest"
onefetch = "latest"
opencode = "latest"
"pipx:hike" = "latest"
podman-tui = "latest"
poppler = "latest"
resvg = "latest"
ripgrep = "latest"
topgrade = "latest"
uv = "latest"
yazi = "latest"
zoxide = "latest"

[settings]
auto_update = true
