[tools]
bun = "latest"
"github:mikeleppane/envx" = "latest"
"github:rgwood/systemctl-tui" = "latest"
node = "25"
"npm:@earendil-works/pi-coding-agent" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:prettier" = "latest"
"pipx:frogmouth-ng" = "latest"
uv = "latest"
